### POST
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "king",
  "password": "king",
  "nama": "apekking",
  "email": "king@test.gmail"
}
### POST
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
"username": "king",
"password": "king"
}