### GET
GET http://localhost:8080/api/kategoris


### GET BY ID
GET http://localhost:8080/api/kategoris/3a39bc5e-c3c1-423c-aae2-7e1fa6c7b32e



### POST
POST http://localhost:8080/api/kategoris
Content-Type: application/json

{
  "nama": "Cemilan"
}

### PUT
PUT http://localhost:8080/api/kategoris
Content-Type: application/json

{
  "id": "3a39bc5e-c3c1-423c-aae2-7e1fa6c7b32e",
  "nama": "indomie kari ayam baru"
}

### DELETE BY ID
DELETE http://localhost:8080/api/kategoris/3a39bc5e-c3c1-423c-aae2-7e1fa6c7b32e