### Get
GET http://localhost:8080/api/penggunas

### Get
GET http://localhost:8080/api/penggunas/

### POST
POST http://localhost:8080/api/penggunas
Content-Type: application/json

{
  "id": "uji",
  "nama": "ahmad fauzi",
  "password":"12345",
  "email": "uji@gmail.com",
  "roles": "uers,admin"
}

### PUT
PUT http://localhost:8080/api/penggunas
Content-Type: application/json

{
  "id": "apekking",
  "nama": "apekking",
  "password":"12345",
  "email": "ilham@gmail.com",
  "roles": "uers,admin"
}

### DELETE BY ID
DELETE http://localhost:8080/api/penggunas/apekking