### GET
GET http://localhost:8080/api/produks


### GET BY ID
GET http://localhost:8080/api/produks/67a91e30-62a2-4f34-938a-ef408580b956



### POST
POST http://localhost:8080/api/produks
Content-Type: application/json

{
  "nama": "Mie kari ayam",
  "kategori": {
    "id" : ""
  },
  "stock": 40,
  "harga": 3.500
}

### PUT
PUT http://localhost:8080/api/produks
Content-Type: application/json

{
  "id": "67a91e30-62a2-4f34-938a-ef408580b956",
  "nama": "taro",
  "kategori": {
    "id" : "f5d6a9d1-4c7b-4d75-972b-266c48890d8e--"
  },
  "stock": 20,
  "harga": 5000
}

### DELETE BY ID
DELETE http://localhost:8080/api/produks/c9984f4a-76f1-4f10-9e1c-cee95e8791fc